defaults: &defaults
  working_directory: /tmp/nomis-api-nginx

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/python:latest-browsers
    steps:
      - checkout
      - setup_remote_docker:
          exclusive: true
      - run:
          command: |
            docker build --rm=false . \
               --tag "mojdigitalstudio/nomis-api-nginx:latest" \
               --label "maintainer=michael.willis@digital.justice.gov.uk" \
               --label "build.number=$CIRCLE_BUILD_NUM" \
               --label "build.url=$CIRCLE_BUILD_URL" \
               --label "build.gitref=$CIRCLE_SHA1"
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mojdigitalstudio/nomis-api-nginx:latest